"""create alerts table

Revision ID: 46c4d08db5d9
Revises: 6d5c6e92a411
Create Date: 2026-06-10 16:15:34.758919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c4d08db5d9'
down_revision: Union[str, Sequence[str], None] = '6d5c6e92a411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tracked_asset_id', sa.Integer(), nullable=False),
    sa.Column('price_check_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['price_check_id'], ['price_checks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracked_asset_id'], ['tracked_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_price_check_id'), 'alerts', ['price_check_id'], unique=False)
    op.create_index(op.f('ix_alerts_tracked_asset_id'), 'alerts', ['tracked_asset_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_tracked_asset_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_price_check_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
