"""create tracked assets and price checks

Revision ID: 6d5c6e92a411
Revises: e2c85daeacb2
Create Date: 2026-06-09 18:03:52.073450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d5c6e92a411'
down_revision: Union[str, Sequence[str], None] = 'e2c85daeacb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_assets_id'), 'tracked_assets', ['id'], unique=False)
    op.create_index(op.f('ix_tracked_assets_symbol'), 'tracked_assets', ['symbol'], unique=False)
    op.create_index(op.f('ix_tracked_assets_user_id'), 'tracked_assets', ['user_id'], unique=False)
    op.create_table('price_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_asset_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tracked_asset_id'], ['tracked_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_checks_id'), 'price_checks', ['id'], unique=False)
    op.create_index(op.f('ix_price_checks_tracked_asset_id'), 'price_checks', ['tracked_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_checks_tracked_asset_id'), table_name='price_checks')
    op.drop_index(op.f('ix_price_checks_id'), table_name='price_checks')
    op.drop_table('price_checks')
    op.drop_index(op.f('ix_tracked_assets_user_id'), table_name='tracked_assets')
    op.drop_index(op.f('ix_tracked_assets_symbol'), table_name='tracked_assets')
    op.drop_index(op.f('ix_tracked_assets_id'), table_name='tracked_assets')
    op.drop_table('tracked_assets')
    # ### end Alembic commands ###
